import os

def create_box(x, y, z, w, h, d, vertex_offset):
    w2, d2 = w / 2.0, d / 2.0
    
    # 8 Vertices
    vertices = [
        (x - w2, y, z + d2),      # 1
        (x + w2, y, z + d2),      # 2
        (x + w2, y + h, z + d2),  # 3
        (x - w2, y + h, z + d2),  # 4
        (x - w2, y, z - d2),      # 5
        (x + w2, y, z - d2),      # 6
        (x + w2, y + h, z - d2),  # 7
        (x - w2, y + h, z - d2)   # 8
    ]
    
    v_str = ""
    for v in vertices:
        v_str += f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n"

    # OBJ format faces are 1-indexed, so we add vertex_offset + 1
    o = vertex_offset
    # standard counter-clockwise quads
    f_str = (
        f"f {o+1} {o+2} {o+3} {o+4}\n"   # front
        f"f {o+8} {o+7} {o+6} {o+5}\n"   # back
        f"f {o+4} {o+3} {o+7} {o+8}\n"   # top
        f"f {o+5} {o+6} {o+2} {o+1}\n"   # bottom
        f"f {o+5} {o+1} {o+4} {o+8}\n"   # left
        f"f {o+2} {o+6} {o+7} {o+3}\n"   # right
    )
    
    return v_str, f_str, vertex_offset + 8

def generate_obj(filepath):
    output = "# Voxel Aztec Warrior Generated by Python\n"
    output += "o Aztec_Warrior\n"
    
    v_all = ""
    f_all = ""
    v_idx = 0
    
    # Torso
    v, f, v_idx = create_box(0, 12, 0, 8, 12, 4, v_idx)
    v_all += v; f_all += f
    # L Leg
    v, f, v_idx = create_box(-2, 0, 0, 4, 12, 4, v_idx)
    v_all += v; f_all += f
    # R Leg
    v, f, v_idx = create_box(2, 0, 0, 4, 12, 4, v_idx)
    v_all += v; f_all += f
    # L Arm
    v, f, v_idx = create_box(-6, 12, 0, 4, 12, 4, v_idx)
    v_all += v; f_all += f
    # R Arm
    v, f, v_idx = create_box(6, 12, 0, 4, 12, 4, v_idx)
    v_all += v; f_all += f
    # Head
    v, f, v_idx = create_box(0, 24, 0, 8, 8, 8, v_idx)
    v_all += v; f_all += f
    
    # Feathers (x5)
    v, f, v_idx = create_box(0, 32, -2, 2, 8, 1, v_idx)
    v_all += v; f_all += f
    v, f, v_idx = create_box(-3, 31, -2, 2, 7, 1, v_idx)
    v_all += v; f_all += f
    v, f, v_idx = create_box(3, 31, -2, 2, 7, 1, v_idx)
    v_all += v; f_all += f
    v, f, v_idx = create_box(-6, 29, -2, 2, 6, 1, v_idx)
    v_all += v; f_all += f
    v, f, v_idx = create_box(6, 29, -2, 2, 6, 1, v_idx)
    v_all += v; f_all += f
    
    output += v_all + "\n" + f_all
    
    with open(filepath, 'w') as file:
        file.write(output)

if __name__ == "__main__":
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "guerrero_azteca_corregido.obj")
    generate_obj(path)
    print(f"File saved to {path}")
